### ISSUE TITLE
Literature

### ISSUE THREAD

**Issue by NVessel** [trickl/trickl-graph#1]
Hello! Could you please tell me what books and articles you used to create this program?

**Comment by trickl** [comment]
Hi, it's been quite a while since I wrote this code - I'd like to help you
out though, was there a particular algorithm that you would like an
academic reference for?

**Comment by NVessel** [comment]
Thank you for attention, I'm interested in planar generation algorithms. So the question is above

**Comment by NVessel** [comment]
Damn, I've got a problem with build. It should get another artifacts with group id like com.trickl but there are no such in maven repos I guess. Is it okay?

**Comment by NVessel** [comment]
@trickl Could you?

**Comment by NVessel** [comment]
@trickl

**Comment by trickl** [comment]
Hi, which particular planar algorithm did you want more information on?

**Comment by NVessel** [comment]
@trickl It's been a while since I wrote this, now I found it. You don't seem to appear online often. How can I contact you? I have a problem with Chrobak, so the layout image is merely one dot where all vertices and edges stay. Is this a bug or a feature? I didn't understand, but my test graph was only K3.

**Comment by NVessel** [comment]
@trickl

**Comment by NVessel** [comment]
@trickl please say how I can connect with you

**Comment by NVessel** [comment]
@trickl please say how I can connect with you

**Comment by NVessel** [comment]
@trickl please say how I can connect with you

**Comment by NVessel** [comment]
@trickl please say how I can connect with you
